/* Generated by wayland-scanner 1.18.0 */

/*
 * Copyright 2022 RDK Management
 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"


static const struct wl_interface *rdkshell_client_control_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
};

static const struct wl_message rdkshell_client_control_requests[] = {
	{ "set_client_bounds_and_scale", "siiuuff", rdkshell_client_control_types + 0 },
	{ "set_client_bounds", "siiuu", rdkshell_client_control_types + 0 },
	{ "set_client_scale", "sff", rdkshell_client_control_types + 0 },
	{ "set_client_properties", "siiuufffii", rdkshell_client_control_types + 0 },
	{ "get_client_properties", "s", rdkshell_client_control_types + 0 },
};

static const struct wl_message rdkshell_client_control_events[] = {
	{ "client_properties", "siiuufffii", rdkshell_client_control_types + 0 },
};

WL_EXPORT const struct wl_interface rdkshell_client_control_interface = {
	"rdkshell_client_control", 1,
	5, rdkshell_client_control_requests,
	1, rdkshell_client_control_events,
};

